%define api.prefix {formula}

%{
#include <iostream>

extern int formulalex();

#define formulaerror printf

#include "fol.hpp"

extern FormulaPtr input_formula;

%}

%union {
	std::string *str_attr;
	TermPtr *term_attr;
	FormulaPtr *formula_attr;
	std::vector<TermPtr> *term_seq_attr;
}

%token<str_attr> SYMBOL;
%token<str_attr> VARIABLE;
%token TRUE;
%token FALSE;
%token NOT;
%token AND;
%token OR;
%token IMP;
%token IFF;
%token FORALL;
%token EXISTS;

%type<formula_attr> formula
%type<formula_attr> quant_formula
%type<formula_attr> iff_formula
%type<formula_attr> imp_formula
%type<formula_attr> or_formula
%type<formula_attr> and_formula
%type<formula_attr> unary_formula
%type<formula_attr> sub_formula
%type<formula_attr> atomic_formula
%type<formula_attr> atom
%type<term_attr> term
%type<term_seq_attr> term_seq

%%

input
	: '"' formula '"' {
		input_formula = *$2;
		delete $2;
		return 0;
	}
	;

formula
	: quant_formula {
		$$ = $1;
	}
	;

quant_formula
	: FORALL VARIABLE  '.' quant_formula {
		FormulaPtr formula = ptr(Quantifier{Quantifier::All, *$2, *$4});
		$$ = new FormulaPtr(formula);
		delete $2;
		delete $4;
	}
	| EXISTS VARIABLE  '.' quant_formula {
		FormulaPtr formula = ptr(Quantifier{Quantifier::Exists, *$2, *$4});
		$$ = new FormulaPtr(formula);
		delete $2;
		delete $4;
	}
	| iff_formula {
		$$ = $1;
	}
	;

iff_formula
	: imp_formula IFF iff_formula {
		FormulaPtr formula = ptr(Binary{Binary::Eq, *$1, *$3});
		$$ = new FormulaPtr(formula);
		delete $1;
		delete $3;
	}
	| imp_formula {
		$$ = $1;
	}
	;

imp_formula
	: or_formula IMP imp_formula {
		FormulaPtr formula = ptr(Binary{Binary::Impl, *$1, *$3});
		$$ = new FormulaPtr(formula);
		delete $1;
		delete $3;
	}
	| or_formula {
		$$ = $1;
	}
	;

or_formula
	: or_formula OR and_formula {
		FormulaPtr formula = ptr(Binary{Binary::Or, *$1, *$3});
		$$ = new FormulaPtr(formula);
		delete $1;
		delete $3;
	}
	| and_formula {
		$$ = $1;
	}
	;

and_formula
	: and_formula AND unary_formula {
		FormulaPtr formula = ptr(Binary{Binary::And, *$1, *$3});
		$$ = new FormulaPtr(formula);
		delete $1;
		delete $3;
	}
	| unary_formula {
		$$ = $1;
	}
	;

unary_formula
	: NOT unary_formula {
		FormulaPtr formula = ptr(Not{*$2});
		$$ = new FormulaPtr(formula);
		delete $2;
	}
	| sub_formula {
		$$ = $1;
	}
	;

sub_formula
	: atomic_formula {
		$$ = $1;
	}
	| '(' formula ')' {
		$$ = $2;
	}
	;

atomic_formula
	: atom {
		$$ = $1;
	}
	| TRUE {
		FormulaPtr formula = trueConst();
		$$ = new FormulaPtr(formula);
	}
	| FALSE {
		FormulaPtr formula = falseConst();
		$$ = new FormulaPtr(formula);
	}
	;

atom
	: SYMBOL {
		FormulaPtr formula = ptr(Atom{*$1, {}});
		$$ = new FormulaPtr(formula);
		delete $1;
	}
	| SYMBOL '(' term_seq ')' {
		FormulaPtr formula = ptr(Atom{*$1, *$3});
		$$ = new FormulaPtr(formula);
		delete $1;
		delete $3;
	}
	;

term_seq
	: term_seq ',' term {
		$1->push_back(*$3);
		$$ = $1;
		delete $3;
	}
	| term {
		$$ = new std::vector<TermPtr>({*$1});
		delete $1;
	}
	;

term
	: VARIABLE {
		TermPtr formula = ptr(Variable{*$1});
		$$ = new TermPtr(formula);
		delete $1;
	}
	| SYMBOL {
		TermPtr formula = ptr(Function{*$1, {}});
		$$ = new TermPtr(formula);
		delete $1;
	}
	| SYMBOL '(' term_seq ')' {
		TermPtr formula = ptr(Function{*$1, *$3});
		$$ = new TermPtr(formula);
		delete $1;
		delete $3;
	}
	;

%%
